### ISSUE TITLE
Cluster Assignment

### ISSUE THREAD

**Issue by bnels** [DeepLearnPhysics/lartpc_mlreco3d#31]
A possible solution to many of the cluster assignment ambiguities:

We seem to have cluster assignment conflicts in delta/michel clusters, because lowest group id is (arbitrarily) prioritized, and the lower group id often belongs to a track.

Since we've already decided on a 5-types label, it seems like the better solution is to favor the group id that has the same type as the 5-types label.

There would still be ambiguities if two particles of the same type (which agrees with the 5-types label) go through the same voxel, but will likely help greatly will michel/delta clusters.

**Comment by francois-drielsma** [comment]
After further discussion, it was agreed upon to allow for shared voxels between multiple groups, instead of arbitrarily assigning a unique group to each voxel. This prior assumption stemmed from the assumption that DBSCAN would produce clusters, but it is no longer valid.

In the previous scheme we had the following schema to import data to the GNN:
- `parse_dbscan`, returns EM DBSCAN clusters produced by type (using `fivetypes` label)
- `parse_cluster3d_clean`, returns unique voxel list with group labels arbitrarily chosen as lowest ID
- `parse_em_primaries`, returns list of EM primary points

In the new scheme we have the following schema:
- `parse_dbscan_groups`, returns EM DBSCAN clusters **produced by group** (using cluster label)
- `parse_cluster3d`, returns **non-unique** voxel list with group labels
- `parse_em_primaries`, unchanged

Please note that `parse_dbscan_groups` now take `cluster3d_mcst` and `particle_mcst` as inputs.

Pull request to follow.

**Comment by francois-drielsma** [comment]
Should close this?

**Comment by francois-drielsma** [comment]
As nobody is objecting, I will close this.
